### ISSUE TITLE
parent() called in constructor, but impossible to set from constructor

### ISSUE THREAD

**Issue by collin** [masylum/Backbone.Subset#4]
As seen here: https://github.com/masylum/Backbone.Subset/blob/master/backbone.subset.js#L23-26

```
Backbone.Subset = function Subset(models, options) {
    options = options || {};

    this.model = this.parent().model;
```

The trouble with this is it effectively turns instances of Backbone.Subset into singletons, you have to define:

```
SomeSubset.prototype.parent = function() { /*....*/ }
```

In such a way that it is very aware of the program implemented around it.

The data inside the instances of a class ought to be passed into the constructor, not the implementation of the class itself.

**Comment by saimonmoore** [comment]
Agreed. At the very least we should both options. Will add this possibility when I can...

**Comment by collin** [comment]
For now I've been using super in coffeescript and more or less eschewing the standard constructor.

```
class Tasks.Subset extends Backbone.Subset
  constructor: (@_parent) -> super()
  parent: -> @_parent
```

Obviously my constructor won't work in the general case. But perhaps parent could be a key on options.

```
this._parent = options.parent;
```

And maybe Subset could have a default implementation for the parent method like mine:

```
return this._parent;
```

What do you think?

**Comment by saimonmoore** [comment]
Something like this?: https://github.com/masylum/Backbone.Subset/pull/5

**Comment by collin** [comment]
Yeah, it's not quite what I did, but I think it simplifies things a bit. thanks for putting that together

**Comment by saimonmoore** [comment]
Pau suggested that perhaps  replacing the calls with attr accesors isn't the wisest thing in case you want to dynamically modify the parent. I can't think of a use case but I think I agree with him.

**Comment by collin** [comment]
That is how i did things. Setting ._parent from the options but having a
default .parent() that returns ._parent

How would Subset react to having the parent swapped? I imagine there would
have to be some event re-binding.

Perhaps .parent() could be a getter/setter and event re/binding could take
place there?

A use case could be connecting a Subset to a view, and then connecting
different collections to that subset without making the view care about
where the data really comes from.

(kind of stretching there, but I could see using it for something if it
worked that way)

**Comment by masylum** [comment]
Already on the master :)
