### ISSUE TITLE
recalculate bug?

### ISSUE THREAD

**Issue by rforte** [masylum/Backbone.Subset#6]
In the reduce function of Subset.recalculate, short-circuit evaluation is causing the right side of:

```
return changed || self._updateModelMembership(model, {silent: true})
```

to never be eval'd once changed becomes true.  This causes sieve to not be called on each element.

Most likely want:

```
return self._updateModelMembership(model, {silent: true}) || changed;
```

**Comment by garbelini** [comment]
Ops! Just sent the exact same fix.

**Comment by bjnsn** [comment]
Noted the exact same issue when changing the sieve and triggering recalculate wasn't achieving expected results.

**Comment by bjnsn** [comment]
This should be closed, fixed by this commit:
https://github.com/masylum/Backbone.Subset/commit/3fe14c5a3f4fcb4962c68358e45048272376c44e
